### PR TITLE
dockerized

### PR DESCRIPTION
**Pull request by PhilippKuntschik**
Dear all,

I created a initial version of docker related scripts that enable our organization to comfortably deploy gerbil on our local servers. Included are:

* `docker_build.sh`, a script to build the docker container on localhost. I have to `-DskipTests` since the current master does not pass all unit-tests (at least immediately after a git pull).
* `run-gerbil.sh` a script that downloads all dependencies and starts the service subsequently. This file contains a `export gerbil_home=~/gerbil/` statement that should be adapted on the target computer.

The scripts represent a quick way to build a docker container. A more elegant solution would a) introduce similar statements to the travis-ci scripts, or b) adapt the Dockerfile to use multi-staging (see: https://blog.docker.com/2017/07/multi-stage-builds/).

Please feel free to adapt everything to your desire, especially the docker-repository. For now, the docker image is available at https://cloud.docker.com/u/philippkuntschik/repository/docker/philippkuntschik/gerbil

cheers, 
phil

### CODE REVIEW

**Comment by nikit91** [comment]
Hi @PhilippKuntschik ,
Your implementation looks pretty good. However, I would like to know if it is possible for you to build the web archive inside another docker container?
This will help us keep the java version used to build the 'war' file uniform across different machines.

**Comment by MichaelRoeder** [comment]
Build issues on master have been fixed.

**Comment by PhilippKuntschik** [comment]
@MichaelRoeder thanks for fixing the CI script. Travis and codacy now finish successfully. 

However, I noticed that the travis.yml file does specifically ignore unit tests as well. Is this behaviour intended?
https://github.com/dice-group/gerbil/blob/master/.travis.yml#L23

On my local machine `mvn clean compile test -U -DskipITs` returns the following result, which seems to be halfway related to issue https://github.com/dice-group/gerbil/issues/304

```bash
Tests in error: 
  test[0](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset OKE 2018 Task 1 training dataset
  test[1](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset DBpediaSpotlight
  test[2](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset ACE2004
  test[3](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset KORE50
  test[4](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset ERD2014
  test[5](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset MSNBC
  test[6](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset GERDAQ-TrainingA

  ...

  test[140](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset OKE 2018 Task 3 training dataset
  test[141](org.aksw.gerbil.execute.GoldStdEvalTest): Couldn't load dataset OKE 2018 Task 4 training dataset
  org.aksw.gerbil.dataset.impl.erd.ERDDatasetTest: The given text file (/workspace/code/thirdparty/gerbil/gerbil_data/datasets/erd2014/Trec_beta.query.txt) does not exist.

Tests run: 543, Failures: 0, Errors: 143, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:25 min
[INFO] Finished at: 2019-01-18T14:16:48+01:00
[INFO] Final Memory: 48M/174M
[INFO] ------------------------------------------------------------------------
```

**Comment by MichaelRoeder** [comment]
Following the documentation of Travis, the line is correct. The install step simply compiles the project. There is a separated test step after that. 
https://docs.travis-ci.com/user/languages/java/#maven-dependency-management

**Comment by PhilippKuntschik** [comment]
Dear all,

I now fixed all codacy problems to my best effort. Unfortunately I could not think of an easy solution without research. In my opinion this issue can be ignored since we do not want to expand the expression anyway.

https://app.codacy.com/app/dice-group/gerbil/pullRequest?prid=2877236

image

If you have any other obligations, please feel free to note them down. From my perspective this is ready to merge now.

**Comment by MichaelRoeder** [comment]
@PhilippKuntschik Thanks a lot for all your effort :+1: 

I checked the final issue from Codacy and from my understanding `-Dexec.args="\${project.version}"` should already fix the problem.

@TortugaAttack @nikit91 I would suggest that we merge it into a new branch, e.g., `ner-docker` (based on master). Otherwise, @PhilippKuntschik would have to perform all the changes that we may want to have since we don't have write access to his branch.
@TortugaAttack if you agree, please take care of it :wink:

**Comment by TortugaAttack** [comment]
will do that

**Comment by TortugaAttack** [comment]
merged it into `ner-docker`

**Comment by MichaelRoeder** [comment]
Now, I am confused... if you merged it, why is the PR still open? :D

**Comment by MichaelRoeder** [comment]
@TortugaAttack I changed the base of this PR, so that you can double check the single line that is left and merge the complete PR.

**Pull request merged**
